### ISSUE TITLE
Font not being loaded when launching from i3

### ISSUE THREAD

**Issue by jpnadas** [fikovnik/st#9]
When I launch st from an i3 binding, it doesn't use the proper font. When I run an identical command (`st -f "Liberation Mono"`) from zsh, the font is properly selected.

Other arguments that I pass to the -f flag in i3 work as expected. For instance, I am able to change the font launching from the i3 binding. So far the only thing that I noticed not to work is the font selection itself.

Here is the pertinent line in my i3 config file `~/.config/i3/config`:
`bindsym $mod+Return exec --no-startup-id st -f "Liberation Mono"`

**Comment by fikovnik** [comment]
Why not change the font config in config.def.h and recompile?

**Comment by jpnadas** [comment]
Hi fikovnik, thanks for the reply.
I have tried changing config.h and the behavior is the same wether I pass the font via argument or compile it by changing the config.h.
That is, the font is properly loaded launching from shell but not launching via i3 keybind.

I have no clue what can be causing this.

**Comment by jpnadas** [comment]
I have now noticed that the problem also occurs when launching st from dmenu.

**Comment by jpnadas** [comment]
Yet another weird thing I found.

To try and go around the issue, I have installed sxhkd and configured a shortcut to launch st.
If I run sxhkd from a terminal, the shortcut works as intended (with the proper font).
It also works if I do so by launching it into the background (with `sxhkd &`).

Howerver, if I add `sxhkd &` to my .xprofile, the shortcut will launch st with the wrong font.

**Comment by jpnadas** [comment]
Ok, it is definately a lightdm issue. I have just disabled lightdm and launched X via startx, no problem whatsoever.

I guess the answer is, ditch lightdm....
